Dutch rules page + layout
dannypas00/Tres pull request #14
Opened 2019-03-28 12:14 UTC by NKN90

2019-03-28 12:19 UTC, monodrail submitted a review, later dismissed
zo kan ik ook wel 7,100 adds krijgen

2019-03-29 10:03 UTC, Mintsjeuh reviewed
Fix titel en blauwe knoppies, voor de rest helemaaal primaaa

2019-03-29 10:03 UTC, Mintsjeuh approved these changes

2019-03-29 11:35 UTC, jorritschippers commented on VS_Project/Pokerapp/Pokerapp/Players.cshtml
> +    urlcode = "1234567";
Graag weer veranderen tot de urlcode niet meer 1234567 is

2019-03-29 11:36 UTC, jorritschippers requested changes
De urlcode moet wel uit de url gehaald worden en niet 1234567 zijn

2019-03-29 12:02 UTC, closed without merging