Updated layout + Working timer
dannypas00/Tres pull request #35
Opened 2019-04-01 14:46 UTC by NKN90

2019-04-01 17:16 UTC, monodrail approved these changes

2019-04-02 08:14 UTC, jorritschippers commented on VS_Project/Pokerapp/Pokerapp/Tableview.cshtml
> -     db.Execute("UPDATE Room SET Small_Blind = @0, Big_Blind = @1 WHERE Room_Code = @2", small, big, roomCode);
Wordt de blind in de room wel geupdate?

2019-04-02 08:14 UTC, jorritschippers commented on VS_Project/Pokerapp/Pokerapp/Tableview.cshtml
> -    int players = db.QueryValue("SELECT COUNT(Name) FROM Players WHERE Room_Code = @0 AND Tbl_nr = @1", roomCode, table);
De reshuffle is weggehaald?

2019-04-02 08:19 UTC, jorritschippers requested changes
In tableview zijn regels 66 t/m 75 weggehaald, dit hoort bij de reshuffle

2019-04-02 08:33 UTC, closed without merging